#define VERSION_MAJOR 2
#define VERSION_MINOR 99
#define VERSION_PATCH 99

#define FIX_VERSION_MAJOR 2
#define FIX_VERSION_MINOR 99
#define FIX_VERSION_PATCH 99

#define ONEKEY_VER_MAJOR 3
#define ONEKEY_VER_MINOR 15
#define ONEKEY_VER_PATCH 0

#define ONEKEY_VERSION "3.15.0"
#define ONEKEY_VERSION_HEX 0x3F00
